template header
id
cpuPriority
gpuPriority
ramPriority

package rules1;

import com.pcadvisor.pcadvisorapi.dto.ComputerProgramRequestDTO;
import com.pcadvisor.pcadvisorapi.dto.PriorityDTO;

template "computer-program-rules"

rule "Computer Program @{id}"
agenda-group "computer-programs"
lock-on-active true
when
    $computerProgram: ComputerProgramRequestDTO(id == @{id})
    $priorityDTO: PriorityDTO()
then
    modify($priorityDTO) { setCpuPriority($priorityDTO.getCpuPriority() + @{cpuPriority}) };
    modify($priorityDTO) { setGpuPriority($priorityDTO.getGpuPriority() + @{gpuPriority}) };
    modify($priorityDTO) { setRamPriority($priorityDTO.getRamPriority() + @{ramPriority}) };
end

end template