package rules1;

import com.pcadvisor.pcadvisorapi.model.CPU;
import com.pcadvisor.pcadvisorapi.model.Motherboard;
import com.pcadvisor.pcadvisorapi.dto.response.CompatibilityResponseDTO;

rule "CheckCompatibilityRule"
    when
        motherboard: Motherboard($chipset: chipset)
        cpu: CPU(compatibleChipsets contains $chipset)
        $compatibility: CompatibilityResponseDTO()
    then
        System.out.println("Compatible");
        $compatibility.setSuccess(true);
    end
