package rules1;

import com.pcadvisor.pcadvisorapi.model.CPU;
import com.pcadvisor.pcadvisorapi.model.Motherboard;
import com.pcadvisor.pcadvisorapi.dto.CompatibilityResponseDTO;

global CompatibilityResponseDTO compatibilityResponse;

rule "CheckCompatibilityRule"
    agenda-group "compatibility"
    when
        motherboard: Motherboard($chipset: chipset)
        cpu: CPU(compatibleChipsets contains $chipset)
    then
        compatibilityResponse.setSuccess(true);
    end
