package rules1;

import com.pcadvisor.pcadvisorapi.model.CPU;
import com.pcadvisor.pcadvisorapi.model.CPUBrand;
import com.pcadvisor.pcadvisorapi.dto.SearchResponseDTO;

global SearchResponseDTO searchResponse;

query findSameCores(CPUBrand cpuBrand, Integer cores)
    cpu: CPU(cpuBrand, cores; )
    or
    CPU(otherBrand, cores; ) and
    findSameCores(otherBrand, cores; )
end

rule "Find same cpu cores"
lock-on-active true
agenda-group "cores-equal"
when
    cpuBrand: CPUBrand($brand: this)
    cores: Integer($cores: this)
    findSameCores($brand, $cores; )
then
    System.out.println("odradio");
    modify(searchResponse) { setSuccess(true) };
end